flowchart LR
%% graph: Marshal

  n1["Label with &quot;quotes&quot;"]
  n2["Label with &lt;brackets&gt;"]
  n3["Label with <br/> newline"]

  n1 -->|edge → with → arrows| n2
  n2 -->|label &amp; symbols &#124; pipes| n3
